#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase

# chmod ug+rwx Allrun Allclean

# Remove decomposeParDict
#rm -f system/decomposeParDict

#------------------------------------------------------------------------------
